# Generated by Django 5.0.1 on 2024-02-27 22:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(default=datetime.date.today)),
                ('appointment_start', models.TimeField()),
                ('appointment_end', models.TimeField()),
                ('consultation_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('appointment_status', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming'), ('on-going', 'On-going'), ('cancelled', 'Cancelled')], default='upcoming', max_length=50)),
                ('appointment_outcome', models.CharField(choices=[('prescribed', 'Prescribed'), ('forwarded', 'Forwarded'), ('awaiting', 'Awaiting'), ('cancelled', 'Cancelled')], default='complete', max_length=50)),
                ('appointment_payment_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CancellationTypes',
            fields=[
                ('cancellation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancellation_type', models.CharField(choices=[('sick leave', 'Sick Leave'), ('on holiday', 'On Holiday'), ('emergency', 'Emergency'), ('incorrect prescription', 'Incorrect Prescription'), ('outdated prescription', 'Outdated Prescription'), ('prescription cancelled (doctor/nurse)', 'Prescription Cancelled (Doctor/Nurse)'), ('prescription cancelled (patient)', 'Prescription Cancelled (Patient)'), ('appointment cancelled (doctor/nurse)', 'Appointment Cancelled (Doctor/Nurse)'), ('appointment cancelled (patient)', 'Appointment Cancelled (Patient)')], default='appointment cancelled (doctor/nurse)', max_length=50)),
                ('individual_type', models.CharField(choices=[('doctor/nurse', 'Doctor/Nurse'), ('patient', 'Patient')], default='doctor/nurse', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_source', models.CharField(choices=[('private', 'Private'), ('nhs', 'NHS')], default='private', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_name', models.CharField(default='default', max_length=150)),
                ('prescription_type', models.CharField(choices=[('liquid', 'Liquid'), ('tablet', 'Tablet'), ('capsules', 'Capsules'), ('drops', 'Drops'), ('inhalers', 'Inhalers')], default='liquid', max_length=50)),
                ('prescription_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRates',
            fields=[
                ('staff_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], default='doctor', max_length=50)),
                ('rate_per_hr', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=150)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('admin', 'Admin')], default='default', max_length=50)),
                ('username', models.CharField(default='default', max_length=50)),
                ('password', models.CharField(default='default', max_length=100)),
                ('gender', models.CharField(choices=[('m', 'M'), ('f', 'F')], default='M', max_length=10)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(default='default', max_length=200)),
                ('phone_number', models.CharField(default='123456789', max_length=20)),
                ('address', models.CharField(default='default', max_length=200)),
                ('postcode', models.CharField(default='default', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentCancellations',
            fields=[
                ('appointment_canellation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='default', max_length=250)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.appointments')),
                ('cancellation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.cancellationtypes')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.patients'),
        ),
        migrations.CreateModel(
            name='PrescriptionsAssignments',
            fields=[
                ('prescription_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prescription_status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('collected', 'Collected'), ('request denied', 'Request Denied')], default='requested', max_length=50)),
                ('issued_date', models.DateField(default=datetime.date.today, null=True)),
                ('quantity', models.IntegerField()),
                ('collection_status', models.CharField(choices=[('awaiting decision', 'Awaiting Decision'), ('waiting to collect', 'Waiting To Collect'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='collected', max_length=50)),
                ('prescription_payment_status', models.BooleanField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.appointments')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.prescriptions')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionCancellations',
            fields=[
                ('prescription_cancellation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='default', max_length=250)),
                ('cancellation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.cancellationtypes')),
                ('prescription_assignment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database_models.prescriptionsassignments')),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('hour_type', models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time')], default='full', max_length=50)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('staff_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.staffrates')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='database_models.users')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database_models.staffs'),
        ),
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='database_models.users'),
        ),
    ]
