# Generated by Django 5.0.1 on 2024-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0002_delete_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionsassignments',
            name='prescription_payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
