# Generated by Django 5.0.1 on 2024-03-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0003_alter_prescriptionsassignments_prescription_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Durations',
            fields=[
                ('duration_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.ImageField(default=1, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('duration', models.CharField(default='1', max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.staffs')),
            ],
        ),
    ]
