# Generated by Django 5.0.1 on 2024-03-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0005_schedules_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durations',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
