# Generated by Django 5.0.1 on 2024-03-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0006_alter_durations_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.durations'),
        ),
    ]
