# Generated by Django 5.0.1 on 2024-03-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0007_alter_slots_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='durations',
            old_name='duration',
            new_name='duration_length',
        ),
    ]
