# Generated by Django 5.0.1 on 2024-03-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0009_alter_slots_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='staff',
        ),
        migrations.AddField(
            model_name='schedules',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], default='monday', max_length=12),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_models.days'),
        ),
    ]
