# Generated by Django 5.0.1 on 2024-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0011_prescriptioncancellations_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('login_attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='default', max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prescription_type',
            field=models.CharField(choices=[('liquid', 'Liquid'), ('tablet', 'Tablet'), ('capsules', 'Capsules'), ('drops', 'Drops'), ('inhalers', 'Inhalers'), ('other', 'Other')], default='liquid', max_length=50),
        ),
    ]
