# Generated by Django 5.0.1 on 2024-04-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0013_users_is_active_alter_users_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationtypes',
            name='cancellation_type',
            field=models.CharField(choices=[('sick leave', 'Sick Leave'), ('on holiday', 'On Holiday'), ('emergency', 'Emergency'), ('deleted user', 'Deleted User'), ('incorrect prescription', 'Incorrect Prescription'), ('outdated prescription', 'Outdated Prescription'), ('prescription cancelled (doctor/nurse)', 'Prescription Cancelled (Doctor/Nurse)'), ('prescription cancelled (patient)', 'Prescription Cancelled (Patient)'), ('appointment cancelled (doctor/nurse)', 'Appointment Cancelled (Doctor/Nurse)'), ('appointment cancelled (patient)', 'Appointment Cancelled (Patient)')], default='appointment cancelled (doctor/nurse)', max_length=50),
        ),
        migrations.AlterField(
            model_name='cancellationtypes',
            name='individual_type',
            field=models.CharField(choices=[('doctor/nurse', 'Doctor/Nurse'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('admin', 'admin'), ('all', 'All')], default='doctor/nurse', max_length=50),
        ),
    ]
