# Generated by Django 5.0.1 on 2024-04-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0014_alter_cancellationtypes_cancellation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrates',
            name='wage_per_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
