# Generated by Django 5.0.1 on 2024-04-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0015_staffrates_wage_per_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='prescription_cost',
        ),
    ]
